name: al_muslim
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter


  ###### ================ UI ================= ######
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  flutter_modular: ^6.3.2
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.1
  toastification: ^2.3.0
  awesome_bottom_bar: ^1.2.4
  pin_code_fields: ^8.0.1
  skeletonizer: ^1.4.3
  video_player: ^2.9.3
  flutter_carousel_widget: ^3.1.0
  photo_view: ^0.15.0


  ###### ================ DATA ================= ######
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.2
  dio: ^5.8.0+1

  ###### ================ UTILS ================= ######
  localize_and_translate: ^6.0.7
  provider: ^6.1.2
  audioplayers: ^6.2.0
  talker: ^4.6.14
  talker_flutter: ^4.6.14
  talker_dio_logger: ^4.6.14
  device_preview: ^1.2.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  local_auth: ^2.3.0
  flutter_qiblah: ^3.1.0+1
  geolocator: ^13.0.1
  geocoding: ^4.0.0
  google_maps_flutter: ^2.14.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.0
  workmanager: ^0.7.0
  quran_library: ^2.2.3+1




  #### ================== FIREBASE ================== ####
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4

  collection: any
  vector_graphics: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  hive_ce_generator: ^1.9.3
  change_app_package_name: 

  # -------- App Icon Launcher ----------#
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  remove_alpha_ios: true

flutter_gen:
  output: lib/core/assets
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/gifs/
    - assets/images/
    - assets/lang/
    - assets/fonts/
    - assets/json/quran/
    - assets/json/khatma/
    - assets/json/azkar/
    - assets/quran_image/

  
  fonts:
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Variable.ttf
          weight: 200
        - asset: assets/fonts/NotoSansArabic-Variable.ttf
          weight: 300
        - asset: assets/fonts/NotoSansArabic-Variable.ttf
          weight: 400
        - asset: assets/fonts/NotoSansArabic-Variable.ttf
          weight: 500
        - asset: assets/fonts/NotoSansArabic-Variable.ttf
          weight: 600
        - asset: assets/fonts/NotoSansArabic-Variable.ttf
          weight: 700
        - asset: assets/fonts/NotoSansArabic-Variable.ttf
          weight: 800
        - asset: assets/fonts/NotoSansArabic-Variable.ttf
          weight: 900
